src/Entity/Produit.php
<?php

namespace App\Entity;
use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use DateTime;
use Doctrine\ORM\Mapping as ORM;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProduitRepository")
 * @UniqueEntity("titre")
 * @Vich\Uploadable
 */
class Produit
{
    function __construct()
    {
        $this->created_at = new DateTime();
        $this->options = new ArrayCollection();
    }

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @var File|null
     * @Assert\Image(
     *     mimeTypes="image/jpeg"
     * )
     * @Vich\UploadableField(mapping="produit_image", fileNameProperty="imageName")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string")
     * @var string|null
     */
    private $imageName;


    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=7, max=50)
     */
    private $titre;
         
    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $descri;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(max=1000, min=45)
     */
    private $prix;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantitie;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $solde;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Option", inversedBy="produits")
     */
    private $options;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getSlug(): string{
       return (new Slugify())->slugify($this->titre); // hello-world
    }

    public function getDescri(): ?string
    {
        return $this->descri;
    }

    public function setDescri(?string $descri): self
    {
        $this->descri = $descri;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getFormattedPrix() : string {
        return number_format($this->prix,0, '', ' ');
    }

    public function getQuantitie(): ?int
    {
        return $this->quantitie;
    }

    public function setQuantitie(int $quantitie): self
    {
        $this->quantitie = $quantitie;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getSolde(): ?bool
    {
        return $this->solde;
    }

    public function setSolde(bool $solde): self
    {
        $this->solde = $solde;

        return $this;
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProduit($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->contains($option)) {
            $this->options->removeElement($option);
            $option->removeProduit($this);
        }

        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File|null $imageFile
     */
    public function setImageFile(?File $imageFile): void
    {
        $this->imageFile = $imageFile;
        // Only change the updated af if the file is really uploaded to avoid database updates.
        // This is needed when the file should be set when loading the entity.
        if ($this->imageFile instanceof UploadedFile) {
            $this->updated_at = new \DateTime('now');
        }
    }

    /**
     * @return string|null
     */
    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    /**
     * @param string|null $imageName
     */
    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

templates/pages/home.html.twig
{% extends "base.html.twig" %}

{% block title 'Samphone Reparation' %}
   
{% block body %}
<div class="jumbotron text-center" >
    <div class="container">
        <h1> Samphone </h1>
         <p> 
            Supported neglected met she therefore unwilling discovery remainder. Way sentiments two
             indulgence uncommonly own. Diminution to frequently sentiments he connection
             continuing indulgence. 
          </p>
    </div>
</div>
<div class="container">
    <h2>Les derniers Smartphones</h2>
    <div class="row flex">
    {% for produit in produits %}
        <div class="col-3">
          <div class="card">
             <div class="card-body">
                 <h5 class="card-title">
                    <a href="{{ path('boutique.show', {id: produit.id, slug: produit.slug}) }}">
                       {{ produit.titre }}
                    </a>
                 </h5>
                  <p class="card-text">  
                        {{ produit.descri }}
                  </p>
                  <div class="text-primary" style="font-weight: bold; font-size: 2rem;">
                        {{ produit.formattedPrix }} €
                  </div>
             </div>
          </div>
        </div>
    {% endfor %}
        
    </div>
</div>
    
{% endblock %}